msg = input('Digite algo: ')
print('O tipo prirmitivo desse valor é', type(msg))
print('Só tem espaços?', msg.isspace())
print('É um número?', msg.isnumeric())
print('É alfabético?', msg.isalpha())
print('É alfanumérico?', msg.isalnum())
print('Está em maiúscula?', msg.isupper())
print('Está em minúscula?', msg.islower())
print('Está capitalizada?', msg.istitle())